/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfazjuego;
/**
 *
 * @author Dylan
 */
public class FrmInterfazJuego extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmInterfazJuego.class.getName());

  
    /**
     * Creates new form frmVista
     */
    public FrmInterfazJuego() {
        
    }
    
        
    
    

    
            

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        rbPrincipiante = new javax.swing.JRadioButton();
        rbIntermedio = new javax.swing.JRadioButton();
        rbAvanzado = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTiempo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblParejas = new javax.swing.JLabel();
        lblValorTiempo = new javax.swing.JLabel();
        lblValorParejas = new javax.swing.JLabel();
        lblValorPuntaje = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();
        lblIntentos = new javax.swing.JLabel();
        lblValorIntentos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelTablero = new javax.swing.JPanel();
        btns33 = new javax.swing.JButton();
        btns34 = new javax.swing.JButton();
        btns25 = new javax.swing.JButton();
        btns26 = new javax.swing.JButton();
        btns27 = new javax.swing.JButton();
        btns28 = new javax.swing.JButton();
        btns49 = new javax.swing.JButton();
        btns50 = new javax.swing.JButton();
        btns35 = new javax.swing.JButton();
        btns36 = new javax.swing.JButton();
        btns29 = new javax.swing.JButton();
        btns30 = new javax.swing.JButton();
        btns31 = new javax.swing.JButton();
        btns32 = new javax.swing.JButton();
        btns51 = new javax.swing.JButton();
        btns52 = new javax.swing.JButton();
        btns37 = new javax.swing.JButton();
        btns38 = new javax.swing.JButton();
        btns1 = new javax.swing.JButton();
        btns2 = new javax.swing.JButton();
        btns3 = new javax.swing.JButton();
        btns4 = new javax.swing.JButton();
        btns53 = new javax.swing.JButton();
        btns54 = new javax.swing.JButton();
        btns39 = new javax.swing.JButton();
        btns40 = new javax.swing.JButton();
        btns5 = new javax.swing.JButton();
        btns6 = new javax.swing.JButton();
        btns7 = new javax.swing.JButton();
        btns8 = new javax.swing.JButton();
        btns55 = new javax.swing.JButton();
        btns56 = new javax.swing.JButton();
        btns41 = new javax.swing.JButton();
        btns42 = new javax.swing.JButton();
        btns9 = new javax.swing.JButton();
        btns10 = new javax.swing.JButton();
        btns11 = new javax.swing.JButton();
        btns12 = new javax.swing.JButton();
        btns57 = new javax.swing.JButton();
        btns58 = new javax.swing.JButton();
        btns43 = new javax.swing.JButton();
        btns44 = new javax.swing.JButton();
        btns13 = new javax.swing.JButton();
        btns14 = new javax.swing.JButton();
        btns15 = new javax.swing.JButton();
        btns16 = new javax.swing.JButton();
        btns59 = new javax.swing.JButton();
        btns60 = new javax.swing.JButton();
        btns45 = new javax.swing.JButton();
        btns46 = new javax.swing.JButton();
        btns17 = new javax.swing.JButton();
        btns18 = new javax.swing.JButton();
        btns19 = new javax.swing.JButton();
        btns20 = new javax.swing.JButton();
        btns61 = new javax.swing.JButton();
        btns62 = new javax.swing.JButton();
        btns47 = new javax.swing.JButton();
        btns48 = new javax.swing.JButton();
        btns21 = new javax.swing.JButton();
        btns22 = new javax.swing.JButton();
        btns23 = new javax.swing.JButton();
        btns24 = new javax.swing.JButton();
        btns63 = new javax.swing.JButton();
        btns64 = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenu.setBackground(new java.awt.Color(204, 204, 204));

        buttonGroup1.add(rbPrincipiante);
        rbPrincipiante.setText("Principiante");
        rbPrincipiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPrincipianteActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbIntermedio);
        rbIntermedio.setText("Intermedio");
        rbIntermedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIntermedioActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbAvanzado);
        rbAvanzado.setText("Avanzado");
        rbAvanzado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAvanzadoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("--- Bienvenido al juego de memoria ---");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Dificultad:");

        lblTiempo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTiempo.setText("Tiempo:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Puntaje:");

        lblParejas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblParejas.setText("Parejas:");

        lblValorTiempo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblValorTiempo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblValorParejas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblValorParejas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblValorPuntaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblValorPuntaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnReiniciar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        lblIntentos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIntentos.setText("Intentos:");

        lblValorIntentos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblValorIntentos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelMenuLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rbPrincipiante)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rbIntermedio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rbAvanzado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReiniciar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelMenuLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblValorPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblParejas)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblValorParejas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblTiempo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblValorTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblIntentos)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblValorIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbPrincipiante)
                    .addComponent(rbIntermedio)
                    .addComponent(rbAvanzado)
                    .addComponent(btnReiniciar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblParejas)
                    .addComponent(lblValorPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorParejas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTiempo)
                    .addComponent(lblValorTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIntentos)
                    .addComponent(lblValorIntentos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)))
        );

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOpaque(true);

        panelTablero.setLayout(new java.awt.GridLayout(8, 8));

        btns33.setActionCommand("33");
        btns33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns33ActionPerformed(evt);
            }
        });
        panelTablero.add(btns33);

        btns34.setActionCommand("34");
        btns34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns34ActionPerformed(evt);
            }
        });
        panelTablero.add(btns34);

        btns25.setActionCommand("25");
        btns25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns25ActionPerformed(evt);
            }
        });
        panelTablero.add(btns25);

        btns26.setActionCommand("26");
        btns26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns26ActionPerformed(evt);
            }
        });
        panelTablero.add(btns26);

        btns27.setActionCommand("27");
        btns27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns27ActionPerformed(evt);
            }
        });
        panelTablero.add(btns27);

        btns28.setActionCommand("28");
        btns28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns28ActionPerformed(evt);
            }
        });
        panelTablero.add(btns28);

        btns49.setActionCommand("49");
        btns49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns49ActionPerformed(evt);
            }
        });
        panelTablero.add(btns49);

        btns50.setActionCommand("50");
        btns50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns50ActionPerformed(evt);
            }
        });
        panelTablero.add(btns50);

        btns35.setActionCommand("35");
        panelTablero.add(btns35);

        btns36.setActionCommand("36");
        panelTablero.add(btns36);

        btns29.setActionCommand("29");
        panelTablero.add(btns29);

        btns30.setActionCommand("30");
        panelTablero.add(btns30);

        btns31.setActionCommand("31");
        panelTablero.add(btns31);

        btns32.setActionCommand("32");
        panelTablero.add(btns32);

        btns51.setActionCommand("51");
        panelTablero.add(btns51);

        btns52.setActionCommand("52");
        panelTablero.add(btns52);

        btns37.setActionCommand("37");
        panelTablero.add(btns37);

        btns38.setActionCommand("38");
        panelTablero.add(btns38);

        btns1.setActionCommand("1");
        btns1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns1ActionPerformed(evt);
            }
        });
        panelTablero.add(btns1);

        btns2.setActionCommand("2");
        panelTablero.add(btns2);

        btns3.setActionCommand("3");
        panelTablero.add(btns3);

        btns4.setActionCommand("4");
        btns4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns4ActionPerformed(evt);
            }
        });
        panelTablero.add(btns4);

        btns53.setActionCommand("53");
        panelTablero.add(btns53);

        btns54.setActionCommand("54");
        panelTablero.add(btns54);

        btns39.setActionCommand("39");
        panelTablero.add(btns39);

        btns40.setActionCommand("40");
        panelTablero.add(btns40);

        btns5.setActionCommand("5");
        panelTablero.add(btns5);

        btns6.setActionCommand("6");
        panelTablero.add(btns6);

        btns7.setActionCommand("7");
        btns7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns7ActionPerformed(evt);
            }
        });
        panelTablero.add(btns7);

        btns8.setActionCommand("8");
        panelTablero.add(btns8);

        btns55.setActionCommand("55");
        panelTablero.add(btns55);

        btns56.setActionCommand("56");
        panelTablero.add(btns56);

        btns41.setActionCommand("41");
        panelTablero.add(btns41);

        btns42.setActionCommand("42");
        btns42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns42ActionPerformed(evt);
            }
        });
        panelTablero.add(btns42);

        btns9.setActionCommand("9");
        panelTablero.add(btns9);

        btns10.setActionCommand("10");
        panelTablero.add(btns10);

        btns11.setActionCommand("11");
        btns11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns11ActionPerformed(evt);
            }
        });
        panelTablero.add(btns11);

        btns12.setActionCommand("12");
        panelTablero.add(btns12);

        btns57.setActionCommand("57");
        panelTablero.add(btns57);

        btns58.setActionCommand("58");
        panelTablero.add(btns58);

        btns43.setActionCommand("43");
        panelTablero.add(btns43);

        btns44.setActionCommand("44");
        panelTablero.add(btns44);

        btns13.setActionCommand("13");
        panelTablero.add(btns13);

        btns14.setActionCommand("14");
        panelTablero.add(btns14);

        btns15.setActionCommand("15");
        panelTablero.add(btns15);

        btns16.setActionCommand("16");
        btns16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns16ActionPerformed(evt);
            }
        });
        panelTablero.add(btns16);

        btns59.setActionCommand("59");
        panelTablero.add(btns59);

        btns60.setActionCommand("60");
        panelTablero.add(btns60);

        btns45.setActionCommand("45");
        panelTablero.add(btns45);

        btns46.setActionCommand("46");
        btns46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns46ActionPerformed(evt);
            }
        });
        panelTablero.add(btns46);

        btns17.setActionCommand("17");
        panelTablero.add(btns17);

        btns18.setActionCommand("18");
        panelTablero.add(btns18);

        btns19.setActionCommand("19");
        panelTablero.add(btns19);

        btns20.setActionCommand("20");
        panelTablero.add(btns20);

        btns61.setActionCommand("61");
        panelTablero.add(btns61);

        btns62.setActionCommand("62");
        panelTablero.add(btns62);

        btns47.setActionCommand("47");
        panelTablero.add(btns47);

        btns48.setActionCommand("48");
        panelTablero.add(btns48);

        btns21.setActionCommand("21");
        panelTablero.add(btns21);

        btns22.setActionCommand("22");
        panelTablero.add(btns22);

        btns23.setActionCommand("23");
        btns23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns23ActionPerformed(evt);
            }
        });
        panelTablero.add(btns23);

        btns24.setActionCommand("24");
        panelTablero.add(btns24);

        btns63.setActionCommand("63");
        panelTablero.add(btns63);

        btns64.setActionCommand("64");
        btns64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btns64ActionPerformed(evt);
            }
        });
        panelTablero.add(btns64);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(panelTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTablero, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void rbAvanzadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAvanzadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAvanzadoActionPerformed

    private void rbIntermedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIntermedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbIntermedioActionPerformed

    private void rbPrincipianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPrincipianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPrincipianteActionPerformed

    private void btns4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btns4ActionPerformed

    private void btns7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btns7ActionPerformed

    private void btns16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btns16ActionPerformed

    private void btns23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btns23ActionPerformed

    private void btns1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btns1ActionPerformed

    private void btns26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btns26ActionPerformed

    private void btns34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btns34ActionPerformed

    private void btns64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btns64ActionPerformed

    private void btns11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btns11ActionPerformed

    private void btns33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btns33ActionPerformed

    private void btns42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btns42ActionPerformed

    private void btns46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btns46ActionPerformed

    private void btns25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btns25ActionPerformed

    private void btns27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btns27ActionPerformed

    private void btns28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btns28ActionPerformed

    private void btns49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btns49ActionPerformed

    private void btns50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btns50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btns50ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmInterfazJuego().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btns1;
    private javax.swing.JButton btns10;
    private javax.swing.JButton btns11;
    private javax.swing.JButton btns12;
    private javax.swing.JButton btns13;
    private javax.swing.JButton btns14;
    private javax.swing.JButton btns15;
    private javax.swing.JButton btns16;
    private javax.swing.JButton btns17;
    private javax.swing.JButton btns18;
    private javax.swing.JButton btns19;
    private javax.swing.JButton btns2;
    private javax.swing.JButton btns20;
    private javax.swing.JButton btns21;
    private javax.swing.JButton btns22;
    private javax.swing.JButton btns23;
    private javax.swing.JButton btns24;
    private javax.swing.JButton btns25;
    private javax.swing.JButton btns26;
    private javax.swing.JButton btns27;
    private javax.swing.JButton btns28;
    private javax.swing.JButton btns29;
    private javax.swing.JButton btns3;
    private javax.swing.JButton btns30;
    private javax.swing.JButton btns31;
    private javax.swing.JButton btns32;
    private javax.swing.JButton btns33;
    private javax.swing.JButton btns34;
    private javax.swing.JButton btns35;
    private javax.swing.JButton btns36;
    private javax.swing.JButton btns37;
    private javax.swing.JButton btns38;
    private javax.swing.JButton btns39;
    private javax.swing.JButton btns4;
    private javax.swing.JButton btns40;
    private javax.swing.JButton btns41;
    private javax.swing.JButton btns42;
    private javax.swing.JButton btns43;
    private javax.swing.JButton btns44;
    private javax.swing.JButton btns45;
    private javax.swing.JButton btns46;
    private javax.swing.JButton btns47;
    private javax.swing.JButton btns48;
    private javax.swing.JButton btns49;
    private javax.swing.JButton btns5;
    private javax.swing.JButton btns50;
    private javax.swing.JButton btns51;
    private javax.swing.JButton btns52;
    private javax.swing.JButton btns53;
    private javax.swing.JButton btns54;
    private javax.swing.JButton btns55;
    private javax.swing.JButton btns56;
    private javax.swing.JButton btns57;
    private javax.swing.JButton btns58;
    private javax.swing.JButton btns59;
    private javax.swing.JButton btns6;
    private javax.swing.JButton btns60;
    private javax.swing.JButton btns61;
    private javax.swing.JButton btns62;
    private javax.swing.JButton btns63;
    private javax.swing.JButton btns64;
    private javax.swing.JButton btns7;
    private javax.swing.JButton btns8;
    private javax.swing.JButton btns9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblIntentos;
    private javax.swing.JLabel lblParejas;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JLabel lblValorIntentos;
    private javax.swing.JLabel lblValorParejas;
    private javax.swing.JLabel lblValorPuntaje;
    private javax.swing.JLabel lblValorTiempo;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelTablero;
    private javax.swing.JRadioButton rbAvanzado;
    private javax.swing.JRadioButton rbIntermedio;
    private javax.swing.JRadioButton rbPrincipiante;
    // End of variables declaration//GEN-END:variables
}
